services:
  api:
    build:
      context: ./api/StarterAPI
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8888/api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
